version: '3'
services:
  postgresdb:
    image: postgres
    # networks:
    #   - backend
    volumes:
      - psql_data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
  dynamodb:
    image: amazon/dynamodb-local
    # networks:
    #   - backend
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    # environment:
    #   - PSQL_DB_URL=${PROTOCOL}://${DB_USER}:${PASSWORD}@${HOST}:${PORT}/${DATABASE}
volumes:
  psql_data:
  dynamodb_data:
#networks:
#  backend:
